-- Generated by apply_theme.sh - do not edit directly
vim.g.colors_name = "generated"

local colors = {
  bg = "#1e1e2e",
  fg = "#cdd6f4",
  accent = "#cba6f7",
  red = "#f38ba8",
  green = "#a6e3a1",
  yellow = "#f9e2af",
  blue = "#89b4fa",
  magenta = "#f5c2e7",
  cyan = "#94e2d5",
  black = "#11111b",
  white = "#cdd6f4",
}

local function set_hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base
set_hl("Normal", { fg = colors.fg, bg = colors.bg })
set_hl("Cursor", { fg = colors.bg, bg = colors.fg })
set_hl("LineNr", { fg = colors.blue })
set_hl("CursorLineNr", { fg = colors.accent, bold = true })
set_hl("StatusLine", { fg = colors.fg, bg = colors.black })
set_hl("StatusLineNC", { fg = colors.fg, bg = colors.black })
set_hl("VertSplit", { fg = colors.black, bg = colors.bg })
set_hl("Search", { fg = colors.black, bg = colors.yellow })
set_hl("IncSearch", { fg = colors.black, bg = colors.yellow })
set_hl("Visual", { bg = colors.blue, fg = colors.black })
set_hl("Comment", { fg = colors.yellow, italic = true })
set_hl("String", { fg = colors.green })
set_hl("Keyword", { fg = colors.magenta, bold = true })
set_hl("Function", { fg = colors.blue })
set_hl("Identifier", { fg = colors.fg })
set_hl("Type", { fg = colors.cyan })
set_hl("Constant", { fg = colors.accent })
set_hl("Error", { fg = colors.red, bold = true })
set_hl("WarningMsg", { fg = colors.yellow, bold = true })

-- Diagnostic colors
set_hl("DiagnosticError", { fg = colors.red })
set_hl("DiagnosticWarn", { fg = colors.yellow })
set_hl("DiagnosticInfo", { fg = colors.blue })
set_hl("DiagnosticHint", { fg = colors.cyan })

-- Treesitter groups (if you use treesitter, these will be overridden)
set_hl("@variable", { fg = colors.fg })
set_hl("@function.call", { fg = colors.blue })
set_hl("@property", { fg = colors.cyan })
set_hl("@string", { fg = colors.green })
set_hl("@keyword", { fg = colors.magenta, bold = true })

