# Catppuccin Mocha
BG=#1e1e2e
FG=#cdd6f4
ACCENT=#cba6f7
ACCENT2=#f5e0dc
RED=#f38ba8
GREEN=#a6e3a1
YELLOW=#f9e2af
BLUE=#89b4fa
MAGENTA=#f5c2e7
CYAN=#94e2d5
BLACK=#11111b
WHITE=#cdd6f4
TRANSPARENT_BG="rgba(30,30,46,0.8)"


# GUI Related Variables
GTK_THEME=catppuccin-mocha-mauve-standard+default
ICON_THEME=Papirus-Dark
CURSOR_THEME=Bibata-Modern-Ice
QT_STYLE=gtk2
