# Hyprlock config
background {
	monitor = 
    path = /home/vickrant/Pictures/Wallpapers/wallpaper
    blur_size = 5
    blur_passes = 2
}

label {
	monitor =
	text = Locked
	color = rgba(255,255,255,1.0)
	font_size = 40
	position = center
}

# Pasword Input
input-field {
	monitor = 
	size = 200, 50
	outline_thickness = 3
	dots_size = 0.33
	dots_spacing = 0.15
	dots_center = true
	fade_on_empty = true
	placeholder_text = <i>Password...</i>
	hide_input = false
	check_color = rgb(204, 136, 34)
	fail_color = rgb(204, 34, 34)
	position = 0, 0
	anchor = center
	halign = center
	valign = center
}

# PAM Authentication
auth {
	pam {
		enabled = true
		module = hyprlock
	}
}

