# Keybinds

$mod = SUPER

# Launch terminal
bind = $mod, Return, exec, kitty

# Launch launcher
bind = $mod, D, exec, rofi -show drun

# Kill focused window
bind = $mod, Q, killactive

# Exit hyprland
bind = $mod, M, exit

# Toggle floating
bind = $mod, V, togglefloating

# Fullscreen
bind = $mod, F, fullscreen

# Lock screen
bind = $mod, L, exec, hyprlock


# ---

# Focus movement
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d


# ---

# Switch workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5


# ---

# Move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5


# ---

# Resize windows
binde = $mod, right, resizeactive, 10 0
binde = $mod, left, resizeactive, -10 0
binde = $mod, up, resizeactive, 0 -10
binde = $mod, down, resizeactive, 0 10


# ---

# Screenshots
bind = , Print, exec, grim - | swappy -f -
bind = $mod SHIFT, S, exec, grim -g "\$(slurp)" - | swappy -f -

